using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ambev.DeveloperEvaluation.ORM.Migrations
{
    /// <inheritdoc />
    public partial class AlterSaleNumberToInt : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
    ALTER TABLE ""Sales"" 
    ALTER COLUMN ""SaleNumber"" TYPE integer USING ""SaleNumber""::integer;
    
    ALTER TABLE ""Sales"" 
    ALTER COLUMN ""SaleNumber"" SET NOT NULL;
    
    CREATE SEQUENCE IF NOT EXISTS ""Sales_SaleNumber_seq""
    OWNED BY ""Sales"".""SaleNumber"";

    ALTER TABLE ""Sales"" 
    ALTER COLUMN ""SaleNumber"" ADD GENERATED BY DEFAULT AS IDENTITY;
");

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "SaleNumber",
                table: "Sales",
                type: "varchar(50)",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer")
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
        }
    }
}
